DROP TABLE IF EXISTS TBL_CATEGORIES;

CREATE TABLE TBL_CATEGORIES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(70) NOT NULL,
    active BOOLEAN NOT NULL 
);

DROP TABLE IF EXISTS TBL_CATEGORY_SCHEDULES;

CREATE TABLE TBL_CATEGORY_SCHEDULES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  schedule_date DATE NOT NULL,
  fk_categories_id INT NOT NULL,
  active BOOLEAN NOT NULL
);

ALTER TABLE TBL_CATEGORY_SCHEDULES ADD FOREIGN KEY ( fk_categories_id ) REFERENCES TBL_CATEGORIES( id );